defmodule PhxHelpdesk.Support.Ticket do
  # This turns this module into a resource
  use Ash.Resource,
    data_layer: AshPostgres.DataLayer,
    extensions: [
      AshGraphql.Resource
    ]

  graphql do
    type :ticket

    queries do
      # <- create a field called `get_ticket` that uses the `read` read action to fetch a single post
      get(:get_ticket, :read)

      # <- create a field called `list_tickets` that uses the `read` read action to fetch a list of posts
      list(:list_tickets, :read)
    end

    mutations do
      # And so on
      create :create_ticket, :create
      update :update_ticket, :update
      destroy :destroy_ticket, :destroy
    end
  end

  postgres do
    table "tickets"
    repo PhxHelpdesk.Repo
  end

  actions do
    # Add a set of simple actions. You'll customize these later.
    defaults [:create, :read, :update, :destroy]
  end

  # Attributes are the simple pieces of data that exist on your resource
  attributes do
    # Add an autogenerated UUID primary key called `:id`.
    uuid_primary_key :id

    # Add a string type attribute called `:subject`
    attribute :subject, :string
  end
end
