defmodule PhxHelpdesk.Repo.Migrations.AddTickets do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tickets, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :subject, :text
    end
  end

  def down do
    drop table(:tickets)
  end
end